// account/src/components/settings/PeriodNameInput.vue
<template>
  <div class="material-input-group">
    <input
      :id="id"
      maxlength="20"
      autocomplete="off"
      class="material-input"
      :class="{ 'has-value': !!value }"
      v-model="value"
    >
    <label :for="id">
      {{ periodName }} {{ isFree ? '- removed from schedule' : '' }}
    </label>
  </div>
</template>

<script>
import { isFreePeriod } from '../../../../common';

export default {
  data() {
    return {
      id: Math.random().toString(36).substring(7),
      isFree: false,
      firstRun: true,
      timeoutId: null,
      value: ''
    }
  },
  props: ['periodName'],
  created() {
    this.value = this.$store.getters.periodNames[this.periodName];
  },
  watch: {
    value() {
      this.isFree = isFreePeriod(this.value);
      this.$store.commit('setPeriodName', { key: this.periodName, value: this.value });
      
      if (!this.firstRun) {
        if (this.timeoutId) {
          clearTimeout(this.timeoutId);
        }

        this.timeoutId = setTimeout(() => {
          this.$ga.event({
            eventCategory: 'settings.period_names.input',
            eventAction: 'changed',
            eventLabel: this.periodName
          });
        }, 5000);
      }
      
      this.firstRun = false;
    }
  }
}
</script>

// account-svelte/src/lib/components/settings/PeriodNameInput.svelte
<script lang="ts">
	import { periodNames, setPeriodName } from '../../store';
	import { onMount } from 'svelte';

	export let periodName: string;

	let id = Math.random().toString(36).substring(7);
	let isFree = false;
	let value = '';

	function isFreePeriod(name: string) {
		if (typeof name !== 'string') return false;
		name = name.trim().toLowerCase();
		return ['free', 'none', 'nothin'].some((a) => name.includes(a));
	}

	function handleInput() {
		isFree = isFreePeriod(value);
		setPeriodName(periodName, value);
	}

	onMount(() => {
		value = $periodNames[periodName] || '';
		isFree = isFreePeriod(value);
	});
</script>

<div class="material-input-group">
	<input
		{id}
		maxlength="20"
		autocomplete="off"
		class="material-input"
		class:has-value={!!value}
		bind:value
		on:input={handleInput}
	/>
	<label for={id}>
		{periodName}
		{isFree ? '- removed from schedule' : ''}
	</label>
</div>
