// account/src/components/PeriodNamesEnter.vue
<template>
  <div>
    <br><br><br>
    <div style="display: flex; margin: 0 auto;">
      <div v-for="column in columns" style="padding: 0 24px; flex: 1;">
        <PeriodNameInput v-for="period in column" :key="period" :period-name="period" />
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex';
import PeriodNameInput from '@/components/PeriodNameInput.vue';

export default {
  components: {
    PeriodNameInput
  },
  computed: {
    ...mapState(['periods', 'school']),
    columns () {
      let columns = []
      let mid = Math.ceil(this.periods.length / 2)
      for (let col = 0; col < 2; col++) {
        columns.push(this.periods.slice(col * mid, col * mid + mid))
      }
      return columns
    },
  },
  watch: {
    school(old, value) {
      if (this.school && old !== value) {
        this.$store.dispatch('loadPeriods');
      }
    }
  }
}
</script>

// account-svelte/src/lib/components/settings/PeriodNamesEnter.svelte
<script>
	import { periods, school, loadPeriods } from '../../store';
	import PeriodNameInput from './PeriodNameInput.svelte';

	let columns = [];

	$: {
		if ($school) {
			loadPeriods($school);
		}
	}

	$: {
		let mid = Math.ceil($periods.length / 2);
		columns = [$periods.slice(0, mid), $periods.slice(mid)];
	}
</script>

<div>
	<div class="margin-top"></div>
	<div class="container">
		<div class="col">
			{#each columns[0] as period (period)}
				<PeriodNameInput periodName={period} />
			{/each}
		</div>
		<div class="col">
			{#each columns[1] as period (period)}
				<PeriodNameInput periodName={period} />
			{/each}
		</div>
	</div>
</div>

<style>
	.margin-top {
		height: 57px;
	}

	.container {
		display: flex;
		margin: 0 auto;
	}

	.col {
		padding: 0 24px;
		flex: 1;
	}

	@media only screen and (max-width: 500px) {
		.margin-top {
			height: 35px;
		}

		.container {
			display: block;
		}

		.col {
			padding: 0 10px;
		}
	}
</style>
