// account/src/components/settings/SaveSettingsButton.vue
<template>
  <button
    class="material-form-button"
    @click="save"
    :disabled="disabled"
  >Save All Settings</button>
</template>

<script>

export default {
  data() {
    return {
      disabled: false
    }
  },
  created() {
    document.onkeydown = e => {
      // support ctrl/cmd + s as saving
      if (e.keyCode === 83 && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
        e.preventDefault();
        if (!this.disabled) {
          this.save();
        }
      }
    }
  },
  destroyed() {
    document.onkeydown = null;
  },
  methods: {
    async save() {
      this.disabled = true;
      await this.$store.dispatch('saveSettings');
      this.$ga.event({
        eventCategory: 'settings.save_settings_button',
        eventAction: 'click'
      });
      setTimeout(() => {
        this.disabled = false;
      }, 2000);
    }
  }
}
</script>

// account-svelte/src/lib/components/settings/SaveSettingsButton.svelte
<script>
	import { saveSettings } from '../../store';
	import { onMount, onDestroy } from 'svelte';

	let disabled = false;

	async function save() {
		disabled = true;
		await saveSettings();
		setTimeout(() => {
			disabled = false;
		}, 2000);
	}

	function handleKeydown(event) {
		if ((event.ctrlKey || event.metaKey) && event.key === 's') {
			event.preventDefault();
			save();
		}
	}

	onMount(() => {
		document.addEventListener('keydown', handleKeydown);
	});

	onDestroy(() => {
		document.removeEventListener('keydown', handleKeydown);
	});
</script>

<button class="material-form-button" on:click={save} {disabled}>Save All Settings</button>
