// main-vue/src/components/main-screen/Canvas.vue
<template>
  <canvas ref="canvas" :style="{ background: theme.b }"></canvas>
</template>

<script>
import { mapState } from 'vuex';

export default {
  props: {
    percentCompleted: Number,
    innerWidth: Number
  },
  data() {
    return {
      canvas: null,
      ctx: null,
      decimalCompleted: 0,
      decimalAnimatingTowards: 0,
      animationInterval: null,
    }
  },
  mounted() {
    this.canvas = this.$refs.canvas;
    this.ctx = this.canvas.getContext('2d');
    this.dimension();
  },
  computed: mapState(['theme']),
  watch: {
    percentCompleted() {
      if (
				(this.percentCompleted < 1 && this.decimalCompleted <= .1 && !this.animationInterval)
				|| (this.percentCompleted > 99 && this.decimalCompleted >= .99)
			) {
				this.draw(this.percentCompleted / 100); // more specific at the beginning or end
			} else if (!this.animationInterval) {
				this.animate(Math.floor(this.percentCompleted) / 100, 2);
			}
    },
    completedColor() {
      this.redraw();
    },
    innerWidth() {
      this.dimension();
    }
  },
  methods: {
    dimension() {
      let dpr = window.devicePixelRatio || 1;
      this.canvas.style.width = window.innerWidth + 'px';
      this.canvas.style.height = window.innerHeight + 'px';
      this.canvas.width = window.innerWidth * dpr;
      this.canvas.height = window.innerHeight * dpr;
      this.ctx.scale(dpr, dpr);

      this.redraw();
    },
    redraw() {
      this.draw(this.decimalCompleted);
    },
    draw(to) {
      let w = window.innerWidth,
        h = window.innerHeight;

      this.ctx.clearRect(0, 0, w, h);

      this.ctx.fillStyle = this.theme.c;
      this.ctx.fillRect(0, 0, to * w, h);

      this.decimalCompleted = to;
    },
    createSineRegression(from, to, length) {
      let amp = (to - from) / 2,
        verticalShift = (from + to) / 2,
        b = (2 * Math.PI) / (2 * length);

		  return x => (amp * (Math.sin(b * (x - (length / 2))))) + verticalShift;
    },
    animate(to, length) {
      if (to === this.decimalAnimatingTowards) return;

      this.decimalAnimatingTowards = to;
      window.cancelAnimationFrame(this.animationInterval); // just for fun!
      delete this.animationInterval;

      let reg = this.createSineRegression(this.decimalCompleted, to, length);
      let startTime = window.performance.now();

      let func = () => {
        let secondsPassed = (window.performance.now() - startTime) / 1e3;
        this.draw(reg(secondsPassed));

        if (length < secondsPassed) {
          window.cancelAnimationFrame(this.animationInterval);
          this.animationInterval = null;
          this.draw(this.decimalAnimatingTowards);
          return;
        }

        window.requestAnimationFrame(func);
      }

      this.animationInterval = window.requestAnimationFrame(func);
    }
  },
}
</script>

// main-svelte/src/lib/components/Canvas.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { preferences } from '$lib/stores/preferences';
	import { timing } from '$lib/stores/timing';

	let canvas: HTMLCanvasElement;
	let ctx: CanvasRenderingContext2D;

	// Animation state management
	let currentProgress = 0; // Current decimal progress (0-1)
	let targetProgress = 0; // Target decimal progress (0-1)
	let isAnimating = false;
	let animationId: number | null = null;
	
	// Animation utilities
	function createSineRegression(from: number, to: number, duration: number) {
		const amp = (to - from) / 2;
		const verticalShift = (from + to) / 2;
		const b = (2 * Math.PI) / (2 * duration);
		
		return (x: number) => amp * Math.sin(b * (x - duration / 2)) + verticalShift;
	}

	const theme = $derived($preferences.theme);
	const screenWidth = $derived($preferences.screenWidth);
	const screenHeight = $derived($preferences.screenHeight);

	onMount(() => {
		ctx = canvas.getContext('2d')!;
		resizeCanvas();
		drawProgress(currentProgress);
		
		// Trigger initial animation to current progress
		const timingData = $timing;
		updateProgress(timingData.decimalCompleted, timingData.showVisuals);
	});

	function resizeCanvas() {
		const dpr = window.devicePixelRatio || 1;
		canvas.style.width = window.innerWidth + 'px';
		canvas.style.height = window.innerHeight + 'px';
		canvas.width = window.innerWidth * dpr;
		canvas.height = window.innerHeight * dpr;
		ctx.scale(dpr, dpr);
		drawProgress(currentProgress);
	}

	function drawProgress(progress: number) {
		if (!ctx) return;

		const w = window.innerWidth;
		const h = window.innerHeight;

		ctx.clearRect(0, 0, w, h);

		const progressWidth = w * progress;

		ctx.fillStyle = theme.c;
		ctx.fillRect(0, 0, progressWidth, h);

		currentProgress = progress;
	}

	// Animation functions
	function animateProgress(to: number, duration: number) {
		if (to === targetProgress) return;
		
		targetProgress = to;
		
		// Cancel any existing animation
		if (animationId) {
			window.cancelAnimationFrame(animationId);
			animationId = null;
		}
		
		// Create sine regression for smooth animation
		const regression = createSineRegression(currentProgress, to, duration);
		const startTime = window.performance.now();
		isAnimating = true;
		
		const animationLoop = () => {
			const secondsPassed = (window.performance.now() - startTime) / 1000;
			
			drawProgress(regression(secondsPassed));
			
			if (duration < secondsPassed) {
				// Animation complete
				window.cancelAnimationFrame(animationId!);
				animationId = null;
				isAnimating = false;
				drawProgress(targetProgress);
				return;
			}
			
			animationId = window.requestAnimationFrame(animationLoop);
		};
		
		animationId = window.requestAnimationFrame(animationLoop);
	}

	function updateProgress(decimalCompleted: number, showVisuals: boolean = true) {
		if (!showVisuals) return;
		
		// Convert to percentage for comparison (matching original logic)
		const percentCompleted = decimalCompleted * 100;
		
		if (
			(percentCompleted < 1 && currentProgress <= 0.01 && !isAnimating) ||
			(percentCompleted > 99 && currentProgress >= 0.99)
		) {
			// Use immediate draw for precision at beginning or end
			drawProgress(decimalCompleted);
		} else if (!isAnimating) {
			// Use smooth animation - floor the percentage then convert back to decimal
			animateProgress(Math.floor(percentCompleted) / 100, 2);
		}
	}

	$effect(() => {
		if (ctx && screenWidth && screenHeight) {
			resizeCanvas();
		}
	});

	$effect(() => {
		if (ctx) {
			const timingData = $timing;
			updateProgress(timingData.decimalCompleted, timingData.showVisuals);
		}
	});
</script>

<canvas bind:this={canvas} id="main-canvas" style:background={theme.b}></canvas>
