// account-svelte/src/lib/components/settings/PeriodNameInput.svelte
<script lang="ts">
	import { periodNames, setPeriodName } from '../../store';
	import { onMount } from 'svelte';

	export let periodName: string;

	let id = Math.random().toString(36).substring(7);
	let isFree = false;
	let value = '';

	function isFreePeriod(name: string) {
		if (typeof name !== 'string') return false;
		name = name.trim().toLowerCase();
		return ['free', 'none', 'nothin'].some((a) => name.includes(a));
	}

	function handleInput() {
		isFree = isFreePeriod(value);
		setPeriodName(periodName, value);
	}

	onMount(() => {
		value = $periodNames[periodName] || '';
		isFree = isFreePeriod(value);
	});
</script>

<div class="material-input-group">
	<input
		{id}
		maxlength="20"
		autocomplete="off"
		class="material-input"
		class:has-value={!!value}
		bind:value
		on:input={handleInput}
	/>
	<label for={id}>
		{periodName}
		{isFree ? '- removed from schedule' : ''}
	</label>
</div>

// account/src/components/PeriodNameInput.vue
<template>
  <div class="material-input-group">
    <input :id="id" maxlength="20" autocomplete="off"
      class="material-form-control"
      :class="{ 'has-value': !!value }"
      v-model="value"
    >
    <label :for="id">
      {{ periodName }} {{ isFree ? '- removed from schedule' : '' }}
    </label>
  </div>
</template>

<script>
import { isFreePeriod } from '../../../common.js';

export default {
  data() {
    return {
      id: Math.random().toString(36).substring(7),
      isFree: false
    }
  },
  props: ['periodName'],
  computed: {
    value: {
      get() {
        let val = this.$store.getters.periodNames[this.periodName];
        this.isFree = isFreePeriod(val);
        return val;
      },
      set(val) {
        this.isFree = isFreePeriod(val);
        this.$store.commit('setPeriodName', { key: this.periodName, val });
      }
    }
  }
}
</script>

<style scoped>
.material-input-group {
  position: relative;
  margin: auto;
  margin-bottom: 60px;
}
input {
  position: relative;
  z-index: 1;
  width: 100%;
  height: 35px;
  font-size: 16px;
  border: none;
  border-bottom: 1px solid #d9d9d9;
  background-color: transparent;
  border-radius: 0;
}
input:disabled {
  cursor: not-allowed;
}
input:focus {
  outline: none;
  border-width: 2px;
  border-color: #4285f4;
  transition: all .2s ease-out;
}
.has-value:valid + label {
  top: -15px;
  color: #757575;
  font-size: 12px;
}
.material-form-control:focus + label {
  top: -15px;
  color: #4285f4;
  font-size: 12px;
}
.material-form-control + label {
  position: absolute;
  top: 10px;
  left: 3px;
  font-size: 16px;
  color: #999999;
  transition: all .2s ease-out;
  z-index: 2;
  cursor: text;
  user-select: none;
}
</style>
